# version: '4' 

# services:
#   rabbitmq:
#     image: rabbitmq:management-alpine
#     tty: true
#     container_name: RBMQ
#     volumes:
#       - rabbitmq_data:/var/lib/rabbitmq # Persistent volume for RabbitMQ data
#     environment:
#       RABBITMQ_DEFAULT_USER: "dev" # Set default RabbitMQ user
#       RABBITMQ_DEFAULT_PASS: "dev12345678" # Set default RabbitMQ password
#     ports:
#       - "4000:15672"
#       - "5672:5672"

#   db:
#     container_name: dbRBMQ
#     image: mysql:latest
#     # command: --default-authentication-plugin=mysql_native_password
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: tutorial
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

#   phpmyadmin:
#     image: phpmyadmin:latest
#     container_name: phpmyadminRBMQ
#     restart: always
#     environment:
#       PMA_HOST: db
#       PMA_USER: root
#       PMA_PASSWORD: root
#     ports:
#       - "8080:80"
#     depends_on:
#       - db

# volumes:
#   rabbitmq_data:
#     driver: local
#   mysql_data:
#     driver: local